### ISSUE TITLE
Please include new postcodes from March 2022

### ISSUE THREAD

**Issue by abdul-imran** [ideal-postcodes/postcodes.io#1010]
Hi,

There were about 4K+ new postcodes introduced onto one of our feed files. We have checked couple of them & cannot see these in Postcodes.IO API. These new postcodes are OX26 9PD and DL15 8FE. These new postcodes were introduced in UK in March 2022.

API URL's to check : 
https://api.postcodes.io/postcodes/OX269PD
https://api.postcodes.io/postcodes/DL158FE

We are not sure how many of these new postcodes out of 4K are missing in Postcodes IO.

**Comment by cblanc** [comment]
Hi Abdul, the problem we have at the minute is that ONS released an incomplete dataset for the most recent update

In May, we identified 77k postcodes with missing ward data and have been waiting for ONS to provide a corrective update

ONS did release an update just yesterday (Jun 29), we're checking to see if this has resolved the problem

**Comment by cblanc** [comment]
Yesterday's release fix the wards issue, unfortunately our tests are finding an additional 246k postcodes with missing parish data. This ONSPD release is still incomplete

**Comment by simion96** [comment]
Hey, we ran into a similar issue and been following this thread. Just wondering if you've had a chance to check if they've fixed the data?

**Comment by cblanc** [comment]
ONS have acknowledged the problem however they're not going to fix ONSPD (GB + NI) May 2022

The August 2022 release is right around the corner, I'm afraid we will need to wait for that. There are too many missing datapoints in this release

**Comment by missinglink** [comment]
I downloaded the file today from https://osdatahub.os.uk/downloads/open/CodePointOpen

The site specifies: "Version Date:2022-08"
The files inside are dated `26 Jul 12:10`

Does that mean the August release has now dropped?

**Comment by cblanc** [comment]
Code-Point Open is the precursor to ONSPD. Essentially it gets rolled up with some other files to make the full dataset

On its own, it's missing too many datapoints to update postcodes.io (in particular Northern Ireland is completely absent)

When OS recognised the mistake they did update CPO - unfortunately it wasn't propagated downstream to ONSPD

As far as I can tell, I can't see ONSPD Aug 22 yet. I'm using the ONS website

<img width="666" alt="image" src="https://user-images.githubusercontent.com/2160685/182868280-11959d1c-465f-49bc-9572-a1caaa37ac98.png">

**Comment by simonziegler** [comment]
I have a missing postcode B26 1BU. Interestingly Google Maps does show this postcode (well, interesting to me anyway!), and the postcode is available from https://osdatahub.os.uk/downloads/open/CodePointOpen. What is the process to get this into your repo and what timing would you expect?

Thank you!

**Comment by missinglink** [comment]
fyi @cblanc the August data has now landed:

<img width="527" alt="Screenshot 2022-08-24 at 11 48 42" src="https://user-images.githubusercontent.com/738069/186387928-af7b4366-b2ce-410b-9290-4304486509a6.png">

**Comment by cblanc** [comment]
Thanks @simonziegler B26 1BU was removed in November 2021 and added back 7 March 2022. Looks like a rebuild

http://postcodes.io/terminated_postcodes/B261BU

**Comment by cblanc** [comment]
ONSPD Aug 2022 available here and docker (14.4.1)

Will deploy to postcodes.io on Monday

**Comment by cblanc** [comment]
Aug 22 update now live

**Comment by missinglink** [comment]
> Hi Abdul, the problem we have at the minute is that ONS released an incomplete dataset for the most recent update
> 
> In May, we identified 77k postcodes with missing ward data and have been waiting for ONS to provide a corrective update
> 
> ONS did release an update just yesterday (Jun 29), we're checking to see if this has resolved the problem

Possibly a bit early to know definitively, but did the previously reported data errors get resolved in the latest Aug 2022 release?

**Comment by abdul-imran** [comment]
I was provided with 2 postcodes on 22nd June to check, OX269PD and DL158FE. 
I can now see DL158FE in Postcodes IO but not OX269PD.

https://api.postcodes.io/postcodes/OX269PD
https://api.postcodes.io/postcodes/DL158FE
