### ISSUE TITLE
AL4 0JB Postcode returns NoneType using the POST method on endpoint https://api.postcodes.io/postcodes

### ISSUE THREAD

**Issue by lukeveitch** [ideal-postcodes/postcodes.io#1025]
The isle of man and channel island postcodes are also missing data. Namely: GY1 1AN, JE3 8FA, IM4 4EQ,IM5 1GR,IM6 1HP

**Comment by lukeveitch** [comment]
The isle of man and channel island postcodes are also missing data. Namely: GY1 1AN, JE3 8FA, IM4 4EQ,IM5 1GR,IM6 1HP

**Comment by cblanc** [comment]
All are available with the August 2022 ONSPD update
