### ISSUE TITLE
hosting in windows server

### ISSUE THREAD

**Issue by kalyannalluri** [ideal-postcodes/postcodes.io#109]
Nice project and excellent efforts. 

I was trying to host this solution in windows server. It was smooth until npm run setup step. 
look like the issue is with shell script  which is written for Linux.  It would be great if instruction for hosting in windows server also provided.

**Comment by cblanc** [comment]
Hi there, thanks for the kind words. I'm afraid I don't have a windows machine to test my suggestions and I'm not very clued in with the windows dev environment, but I hope you can bear with me.

The OS agnostic instructions that the setup script runs is:
1) Download and unpack the `pg_dump` - latest is here: https://postcodesio.s3.amazonaws.com/public/postcodesio-2017-03-06-1509.sql.gz
2) Enable PostGIS in postgresql
3) Create a database in postgresql to house the data
4) Import the above unpacked pg_dump file (requires superuser credentials for postgresql)
5) Create a user which can read the database you just created, make sure the credentials specified in config/config.js match your database credentials. Better yet, pass them in as ENV variables e.g. `POSTGRES_USER='postcodesio_user'` - listed [here](https://github.com/ideal-postcodes/postcodes.io/blob/master/config/config.js#L105)

Now to make them more specific for windows:
1) I understand winzip or [7-zip](http://www.7-zip.org/) can unpack .gz files
2) This is just a matter of executing the statement `CREATE EXTENSION postgis`. If postgresql does not come with postgis bundled, you can grab a copy at http://postgis.net/windows_downloads/
3) I think most people access postgresql via some form of command line in windows. So this should be a matter of `createdb <database_name>`
4) I think you can use `pg_restore` to import the unpacked pg_dump in windows, the documentation for that utility can be found here: https://www.postgresql.org/docs/9.5/static/app-pgrestore.html
5) Now you're back in node.js land, so you can run with `node server.js`. You can configure the ENV variables with `set POSTGRES_USER=foo` - SO answer is here http://stackoverflow.com/questions/9249830/how-can-i-set-node-env-production-in-windows

Let me know if you run into any issues

**Comment by kalyannalluri** [comment]
Excellent. You made my day :)   
Finally I was able to host it in windows server.  Thank you very much.

pg_restore  didn't work for me because of the dump format. Had to use PSQL instead.

**Comment by cblanc** [comment]
Ah yes, good point. pg_restore is for non-plaintext pg_dumps

If you find any gotchas for windows hosting, am quite keen to document them in /documentation 

Thanks!

**Comment by mtmail** [comment]
@cblanc From other projects I learned there's CI for windows platform https://www.appveyor.com/ (free for open source). I never set one up though.

**Comment by cblanc** [comment]
Thanks, looks like it has a free tier for os projects. Will give it a go
