### ISSUE TITLE
Provide a way to view the last time data was pulled

### ISSUE THREAD

**Issue by cyrus01337** [ideal-postcodes/postcodes.io#1156]
At the moment, I don't see a way to do this, though I may be mistaken. It would be very helpful to know the latest pull from ONSDB (if that is the only source) that was used either on the README or through some sort of notification.

**Comment by cblanc** [comment]
This is on the `/about` page. However this time I forgot to update. Should show Feb 2023. 

May 2023 due shortly

**Comment by cblanc** [comment]
<img width="1055" alt="image" src="https://github.com/ideal-postcodes/postcodes.io/assets/2160685/4a6f176f-d7e4-4728-925e-2ad8bf299d59">
