### ISSUE TITLE
How to use axios?

### ISSUE THREAD

**Issue by kossa** [ideal-postcodes/postcodes.io#1167]
Hello,

I'm using axios to get data, I'm getting this error: 

![image](https://github.com/ideal-postcodes/postcodes.io/assets/1175584/7648a345-dfc7-4d94-9a68-7b3226f17adf)

**Comment by cblanc** [comment]
You need to query a valid url, then a CORS header will be provided

E.g. `https://api.postcodes.io/postcodes/NN180ES`

<img width="360" alt="image" src="https://github.com/ideal-postcodes/postcodes.io/assets/2160685/a6ea3806-9272-4017-b87d-15ad350b6ab6">
