### ISSUE TITLE
Data update to ONSPD May 2023 enquiry.

### ISSUE THREAD

**Issue by itsozz** [ideal-postcodes/postcodes.io#1174]
Hi, firstly thanks very much for providing such a great resource!  Just wondering when the latest ONSPD data (May 2023) will be available in postcodes.io?  A number of Local Authorities including Trafford had ward changes following review by the Electoral Boundary Commission which came into effect from the local elections on 2023-05-04.  These changes are captured in the ONSPD May 2023 dataset and it would be really useful to have them available via postcodes.io.  Appreciate this is simply a question of when a data update is happening rather than there being an issue with the application!  Thanks.

**Comment by cblanc** [comment]
Hi there. The cause of the delay is the same as before, the initial release always seems to be large gaps in the data. I see an updated May2023 release is available as of a couple weeks ago - I'll check that out today

**Comment by itsozz** [comment]
Thanks very much for your quick response, and for looking into things today, really appreciated!  Happy for this to be closed now, or whenever you prefer.

**Comment by cblanc** [comment]
Looks like the gaps are still there

I've decided to update the file as is. It will be live on postcodes.io by Wednesday
