### ISSUE TITLE
Parliamentary constituency boundary changes

### ISSUE THREAD

**Issue by tomwalkr** [ideal-postcodes/postcodes.io#1180]
Apologies if I missed a discussion of this elsewhere. 

Do you have a plan for how to handle the forthcoming boundary changes to parliamentary constituencies? See https://boundarycommissionforengland.independent.gov.uk/2023-review/

Since it is a large and rare change, it would be useful for my (admittedly quite particular!) use case if it were possible to retrieve both the old and new parliamentary_constituency as separate fields. Current MPs continue to sit in the 'old' constituencies until the forthcoming general election, but the election will then be held under the new boundaries.

**Comment by cblanc** [comment]
Hi @tomwalkr 

Postcodes.io will report whatever is current in ONSPD. 

To accommodate the change you're requesting would require substantial reworking of the code, as we would have to older versions of ONSPD as well as latest

I think the best solution here is to run 2 copies of postcodes.io. Each release of ONSPD is accompanied with a new release version of postcodes.io DB tracked in the changelog. You can extract from older versions of ONSPD just be changing the version number of the docker image

**Comment by tomwalkr** [comment]
OK, thanks! Others may run into this because the two will in effect run concurrently for a period (ie. your constituency for the coming election is different to the constituency for the sitting MP). But I can see that ultimately it depends on how ONSPD plans to handle this.

**Comment by mashedkeyboard** [comment]
Hi @cblanc, there currently appears to be a discrepancy between postcodes.io's data output and the constituencies in the latest ONSPD - I'm assuming owing to an error?

For example, W2 5HT returns its constituency as Kensington and Bayswater, a constituency that doesn't yet exist. Yet, in ONSPD Feb 2024, that postcode corresponds to `E14001036`, Westminster North, which is its correct constituency under the present boundaries.

**Comment by cblanc** [comment]
Hi @mashedkeyboard I forgot this was how I promised to handle the change

Tomorrow I'll cut a new release that puts the 2024 constituencies in a new field

**Comment by cblanc** [comment]
Deployed @mashedkeyboard
