### ISSUE TITLE
MK9 1UP is rejected but is valid

### ISSUE THREAD

**Issue by violuke** [ideal-postcodes/postcodes.io#1183]
Thanks for the great package.

We've never had any trouble with it before, but MK9 1UP is being rejected

<img width="808" alt="Screenshot 2024-01-11 at 09 25 05" src="https://github.com/ideal-postcodes/postcodes.io/assets/6420347/9ca73ee8-fc14-4c64-86ab-696ddd077d37">

And isn't terminated

<img width="808" alt="Screenshot 2024-01-11 at 09 25 25" src="https://github.com/ideal-postcodes/postcodes.io/assets/6420347/812f66f3-8f30-4439-96ce-d02ff4391f47">

And [Royal Mail](https://www.royalmail.com/find-a-postcode) are happy with it

<img width="1031" alt="Screenshot 2024-01-11 at 09 25 50" src="https://github.com/ideal-postcodes/postcodes.io/assets/6420347/0f663301-8906-4758-8201-023fbf56c909">

Can you help? Thank you.

**Comment by cblanc** [comment]
Fixed in latest ONSPD release
