### ISSUE TITLE
Some Northern Ireland postcodes return English constituencies for 2024

### ISSUE THREAD

**Issue by pentri** [ideal-postcodes/postcodes.io#1192]
I use the postcodes.io API and a user has drawn my attention to the fact that for some postcodes in Northern Ireland, the 2024 constituency data being returned by my app (based on your API) is incorrect. 

e.g. BT16 1AW

{
    "status": 200,
    "result": {
        "postcode": "BT16 1AW",
        "quality": 1,
        "eastings": 343424,
        "northings": 372714,
        "country": "Northern Ireland",
        "nhs_ha": "Health & Social Care Board",
        "longitude": -5.782421,
        "latitude": 54.582341,
        "european_electoral_region": "Northern Ireland",
        "primary_care_trust": "Belfast",
        "region": null,
        "lsoa": "Carrowreagh 1",
        "msoa": null,
        "incode": "1AW",
        "outcode": "BT16",
        "parliamentary_constituency": "Belfast East",
        "parliamentary_constituency_2024": "Runcorn and Helsby",
        "admin_district": "Lisburn and Castlereagh",
        "parish": null,
        "admin_county": null,
        "date_of_introduction": "201809",
        "admin_ward": "Carrowreagh",
        "ced": null,
        "ccg": "Belfast",
        "nuts": "Lisburn and Castlereagh",
        "pfa": "(pseudo) Northern Ireland",
        "codes": {
            "admin_district": "N09000007",
            "admin_county": "N99999999",
            "admin_ward": "N08000709",
            "parish": "N99999999",
            "parliamentary_constituency": "N06000001",
            "parliamentary_constituency_2024": "E14001455",
            "ccg": "ZC010",
            "ccg_id": "ZC010",
            "ced": "N99999999",
            "nuts": "TLN0E",
            "lsoa": "95II04S1",
            "msoa": "N99999999",
            "lau2": "N09000007",
            "pfa": "N99999999"
        }
    }
}

**Comment by cblanc** [comment]
Thanks for highlighting this. Believe its because the constituencies are inferred using Northings/Eastings and NI uses a different coordinate system to the UK. Should be straightforward to fix

**Comment by pentri** [comment]
Hi Christopher - I noticed some commits recently but it looks like Belfast postcodes such as BT1 1AA are still returning erroneous parliamentary_constituency_2024 values.
 
I wondered if you had an ETA on the fix you mentioned above? 

I really appreciate your work, and recognise you must be busy.

**Comment by cblanc** [comment]
Sincere apologies for the wait @pentri - I've just shipped a release to fix this

I've been hesitant to make promises on this project. But the announcement of the election and the release of May 2024 ONSPD forced me to clear my day for this

This release contains a manually compiled list of Postcodes and 2024 constituencies. It fixes the issue with Northern Ireland and adds Scotland

Once the CI passes it should ship tomorrow as 16.0.0

**Comment by pentri** [comment]
Ah, thanks so much! Will keep an eye out for the data coming through on the Postcodes.io API. Very much appreciated :)

**Comment by cblanc** [comment]
Thanks for your patience. 16.0.0 is live

**Comment by pentri** [comment]
Thanks - just to check, the NI postcodes I've tested are no longer returning erroneous English 2024 constituencies, but are just returning 'null' in the API now. Is this a matter of time or is there an ongoing issue still?

examples: BT48 7EL (should be Foyle, I think), and BT1 1AA (should be Belfast North)

thanks

**Comment by cblanc** [comment]
Thanks for reporting this, I'll take a look

**Comment by cblanc** [comment]
Fix available shortly in 16.0.1
