### ISSUE TITLE
Outcode response should include country

### ISSUE THREAD

**Issue by neilbmclaughlin** [ideal-postcodes/postcodes.io#120]
Given that the outcode response includes local area information it seems odd for it not to include the county property too. The service we are building is England specific and we need to handle the scenario where someone uses a non-England outcode. This requires us to make two calls rather than just one.

Happy to fork and create a PR if you are happy to accept PR's (README doesn't describe contribution guidelines).

**Comment by neilbmclaughlin** [comment]
I had assumed that an outcode would not span countries but a quick bit of investigation suggests this is not true. An example would be TD which is for Galshiels and spans the Scottish/English border. This suggests that the country property should be an countries (an array of strings). I also assume this makes the problem slightly harder to solve.

**Comment by cblanc** [comment]
I wouldn't be averse to adding this

A PR would probably involve:
1) Extending the [outcode schema](https://github.com/ideal-postcodes/postcodes.io/blob/master/app/models/outcode.js) to include an array of string for country
2) Extend [Postcode.findOutcode](https://github.com/ideal-postcodes/postcodes.io/blob/master/app/models/postcode.js#L527) to return countries
2a) Add an additional attributes query to pull a unique an array of countries [like this](https://github.com/ideal-postcodes/postcodes.io/blob/master/app/models/postcode.js#L493)
2b) Update [this](https://github.com/ideal-postcodes/postcodes.io/blob/master/app/models/postcode.js#L520) to properly handle empty results

I think once the above steps are complete, rebuilding the outcodes table should properly populate countries in an array

**Comment by beseven** [comment]
A bit biased, as I work with @neilbmclaughlin, but this would be ace.
👍

**Comment by cblanc** [comment]
Have a working branch [here](https://github.com/cblanc/postcodes.io) which implements the above

Since there's a small data migration, will probably only get around to updating https://postcodes.io at some point next week

```
GET /outcodes/sw1a
{
   "status":200,
   "result":{
      "outcode":"SW1A",
      "longitude":-0.132464059102343,
      "latitude":51.503519328531,
      "northings":179940,
      "eastings":529716,
      "admin_district":[
         "Westminster",
         "Wandsworth"
      ],
      "parish":[
         "Westminster, unparished area",
         "Wandsworth, unparished area"
      ],
      "admin_county":[

      ],
      "admin_ward":[
         "Queenstown",
         "St James's"
      ],
      "country":[
         "England"
      ]
   }
}
```

**Comment by neilbmclaughlin** [comment]
Thanks for the quick response. Look forward to the fix appearing on postcodes.io.

**Comment by cblanc** [comment]
Deployed it just now
