### ISSUE TITLE
Isle of Man/Channel Islands: API not providing longitude/latitude data.

### ISSUE THREAD

**Issue by Heroic-ignorance** [ideal-postcodes/postcodes.io#1200]
Hi,

Recently I have been unable to make changes to our website pages for the Isle of Man and the Channel Islands.

Our website developer has told me this is because Postcodes.io does not return longitude or latitude data for these postcode lookups, which our website architecture apparently needs to confirm before it will re-save these pages.

I am unclear if this is a new issue or not, nor how I can confirm this issue in the data set myself (amateur hour I'm afraid...).

Issue does not affect the Shetlands or Isle of Wight, so seems (perhaps) related to these areas not being part of the United Kingdom proper?  No idea why that would be a problem, but does seem to be the common denominator.

Thanks,

**Comment by Heroic-ignorance** [comment]
Postcodes areas not providing longitude/latitude data:  IM1, IM2, IM3, IM4, IM5, IM6, IM7, IM8, IM9 & GY1, GY2, GY3, GY4, GY5, GY6, GY7, GY8, GY9.

(Also I worked out how to check, and yes none of these return that specific locational data).

**Comment by cblanc** [comment]
This is not provided in ONSPD I'm afraid
