### ISSUE TITLE
Some latitudes + longitudes return null

### ISSUE THREAD

**Issue by lewis-conroy** [ideal-postcodes/postcodes.io#1201]
Example data:
- latitude: 52.80825300
- longitude: -1.47283400

the return value is null

**Comment by cblanc** [comment]
You can either increase the `radius=` or use `widesearch=true`

<img width="982" alt="image" src="https://github.com/user-attachments/assets/a00406fd-ef21-4cb8-a77e-0f9c497a4b55">
