### ISSUE TITLE
Showing wrong constituencies

### ISSUE THREAD

**Issue by nuno-miranda** [ideal-postcodes/postcodes.io#1203]
Hi, I noticed after the last updated (17.0.0) started to show wrong 2024 constituencies.

A few examples:
https://api.postcodes.io/postcodes/PH128TG
is showing "Perth and North Perthshire" instead of "Angus and Perthshire Glens"

https://api.postcodes.io/postcodes/SW9%209SZ 
is showing "Vauxhall" instead of "Clapham and Brixton Hill"

Seems that is showing now pre 2024 elections.

Thanks!

Kind regards,
Nuno

**Comment by cblanc** [comment]
Have rolled this back this morning

According to this release, the constituencies should all be 2024. However it looks as though something has gone wrong. 

ONS has just re-released ONSPD Aug, hopefully this update should fix the pcons issue

**Comment by nuno-miranda** [comment]
Hi @cblanc , thank you for that fix.

Seems that with the new push from today, the previous issue started to happen again.

A few examples:
https://api.postcodes.io/postcodes/PH128TG
is showing "Perth and North Perthshire" instead of "Angus and Perthshire Glens"

https://api.postcodes.io/postcodes/SW9%209SZ
is showing "Vauxhall" instead of "Clapham and Brixton Hill"

Thank you!

Kind regards,
Nuno

**Comment by cblanc** [comment]
Thanks Nuno

Am digging into the issue tomorrow

It seems like if you run 17.0.1 locally, the amended version of ONSPD is supplied. But the production images seem to return stale data - hopefully its just a caching issue

**Comment by cblanc** [comment]
It was caching after all. Thanks for raising this
