### ISSUE TITLE
404 error for a postcode that exists on maps

### ISSUE THREAD

**Issue by block-01** [ideal-postcodes/postcodes.io#1205]
Hi, I was wondering when the postcodes were last updated in the api as I've just tried a `CF10` postcode however it returned a 404 error however when I search up that same postcode on google maps it exists. I'm nowhere near Cardif so I'm unable to check for myself if it exists or not

**Comment by cblanc** [comment]
Hi @block-01 CF10 is an example of an outward code (i.e. the first half of a postcode)

You can use the following API to find aggregated information for specific outcodes

http://api.postcodes.io/outcodes/cf10

**Comment by block-01** [comment]
Ok, I didn't want to put the full postcode in the issue as I didn't know if it was appropriate to put that in the issue but if you would like the full postcode I can provide it
