### ISSUE TITLE
Natural ordering of addresses

### ISSUE THREAD

**Issue by TeamKinetic** [ideal-postcodes/postcodes.io#131]
Hi there,

The addresses that are returned are ordered alpha/numerically but not naturally so 10-19 comes before 2.

**Comment by cblanc** [comment]
Hi @TeamKinetic 

Could you give an example API request?

Thanks

**Comment by TeamKinetic** [comment]
so sorry..too many windows open..different postcode API!

**Comment by cblanc** [comment]
No worries (-:
