### ISSUE TITLE
No postcode found error for postcode: E15 2EN

### ISSUE THREAD

**Issue by ktusharprdxn** [ideal-postcodes/postcodes.io#133]
<img width="293" alt="valid-postcode" src="https://user-images.githubusercontent.com/10720760/28776338-dec2eee8-7613-11e7-943e-8e4975dee649.png">
I am getting no postcode found error for this postcode.

**Comment by cblanc** [comment]
Hi @ktusharprdxn

`E15 2EN` was terminated February 2015 - you can verify this on the ONPSD May 2017 dataset
