### ISSUE TITLE
Include OS Grid Reference code from /postcodes/<postcode>

### ISSUE THREAD

**Issue by Antaris** [ideal-postcodes/postcodes.io#142]
Is it possible to get the OS grid reference code as part of the response?

**Comment by cblanc** [comment]
Hi there

Are you referring to the six figure grid reference? E.g. NN 166 712.

**Comment by cblanc** [comment]
It should be possible to produce an OS Grid Reference using the Northings/Eastings provided:

http://www.movable-type.co.uk/scripts/latlong-os-gridref.html
