### ISSUE TITLE
Map To Registry Error

### ISSUE THREAD

**Issue by minnie-tan** [ideal-postcodes/postcodes.io#158]
I'm new to git and everything about how the open community works if I want to contribute.  I'm interested to learn this project because I applied for study and one of my proposals is about postcode. I just want to ask permission if I can use the source and help contribute to this postcodes.io, because I want to learn and give back, unless I'm in a community I'm inefficient learning on my own. Though I have a background as a developer, it's more on the legacy applications. 
I'm also getting an error mapping to registry as attached.
[npm-debug.log](https://github.com/ideal-postcodes/postcodes.io/files/1491146/npm-debug.log)

**Comment by cblanc** [comment]
Postcodes.io isn't published on npm

The easiest way to clone it would be to use `git clone`

i.e.

```bash
git clone git@github.com:ideal-postcodes/postcodes.io.git
```
