### ISSUE TITLE
The Postcode SE17EW not working

### ISSUE THREAD

**Issue by atanmayprdxn** [ideal-postcodes/postcodes.io#171]
The postcode for api.postcodes.io/postcodes/SE17EW is not working.
Check this google search - https://goo.gl/oT2vT1.
Please let me know if this is working as expected or not.
@cblanc ^^.

**Comment by cblanc** [comment]
SE1 7EW was dropped in 2010

There's a handy endpoint to help determine whether a postcode has been terminated: 

```
http://postcodes.io/terminated_postcodes/:postcode
```

[Quick link](http://postcodes.io/terminated_postcodes/se17ew)
