### ISSUE TITLE
Bulk Reverse Geocoding

### ISSUE THREAD

**Issue by amealing** [ideal-postcodes/postcodes.io#185]
Doesn't seem to work at the moment, probably my end but can't find the error:

Sending a post request with data: 
{'geolocations': [{'latitude': 51.5709997, 'radius': 500, 'longitude': 0.0846147, 'wideSearch': None}]} 

Returns: 
{"status":200,"result":[{"query":"latitude","result":null},{"query":"radius","result":null},{"query":"longitude","result":null},{"query":"wideSearch","result":null}]}

**Comment by cblanc** [comment]
Hi there,

Could you try posting with this data

```
{"geolocations": [{"latitude": 51.5709997, "radius": 500, "longitude": 0.0846147, "wideSearch": false}]}
```

**Comment by cblanc** [comment]
Not sure if that's JSON you're posting or native object notation for a language I'm not familiar with. 

If its the former:
-you will need double quotes i.e. `"` instead of `'`
- Also `None` needs to be boolean e.g. `true` or `false`

**Comment by amealing** [comment]
Hi Chris,

Thanks for the response. The problem was indeed with the quotes.

Cheers
Alex
