### ISSUE TITLE
List off addresses for post code

### ISSUE THREAD

**Issue by woldsnewmedia** [ideal-postcodes/postcodes.io#190]
Is it possible with postcodes.io to obtain a list such as this by post code?

{
  "latitude": 54.9872162,
  "longitude": -1.5494137,
  "addresses": [
    "1002a Shields Road, , , , , Newcastle upon Tyne, Northumberland",
    "1004 Shields Road, , , , , Newcastle upon Tyne, Northumberland",
    "1006 Shields Road, , , , , Newcastle upon Tyne, Northumberland",
    "1008 Shields Road, , , , , Newcastle upon Tyne, Northumberland",
    "1010 Shields Road, , , , , Newcastle upon Tyne, Northumberland",
    "1012 Shields Road, , , , , Newcastle upon Tyne, Northumberland",
    "1014 Shields Road, , , , , Newcastle upon Tyne, Northumberland",
    "1016 Shields Road, , , , , Newcastle upon Tyne, Northumberland",
    "1018 Shields Road, , , , , Newcastle upon Tyne, Northumberland",
    "1020 Shields Road, , , , , Newcastle upon Tyne, Northumberland",
    "1022 Shields Road, , , , , Newcastle upon Tyne, Northumberland",
    "1024 Shields Road, , , , , Newcastle upon Tyne, Northumberland",
    "Abitovadu Costume Hire & Sales, 1000 Shields Road, , , , Newcastle upon Tyne, Northumberland",
    "Aboc Solid Fuels, 1000 Shields Road, , , , Newcastle upon Tyne, Northumberland",
    "Chelle, 998 Shields Road, , , , Newcastle upon Tyne, Northumberland",
    "Short Cuts Barber Shop, 1002 Shields Road, , , , Newcastle upon Tyne, Northumberland"
  ]
}

**Comment by cblanc** [comment]
Hi there,

I'm afraid not, no. There's no freely available dataset that permits something like that for the UK - so it's not something postcodes.io currently provides or could provide (unless something changes in the future)

**Comment by baselakasha** [comment]
Any updated on this, has the situation changed?

**Comment by cblanc** [comment]
@baselakasha I'm afraid not
