### ISSUE TITLE
Wider search radius

### ISSUE THREAD

**Issue by tomchambers2** [ideal-postcodes/postcodes.io#23]
Any chance of getting a wider search radius for the search by lat lng. I'm making a map where dragging loads new search results for the new coordinates and I need to get a postcode to search by. Often it ends up outside of the 1km range of the nearest postcode. For example:
```
A453, Derby, Leicestershire DE73 8BB, UK
Latitude : 52.809403 | Longitude : -1.361275
```

**Comment by cblanc** [comment]
Thanks for the feedback. What kind of range is ideal? Would 2km suffice for general use?

Should be a relatively quick fix, it's just a matter of tweaking the configuration file. https://github.com/ideal-postcodes/postcodes.io/blob/master/config/config.js#L8

**Comment by cblanc** [comment]
I played with the radii for a while. I was able to the postcode you specified after bumping it to just 2km. Apologies for being a bit reluctant to push the maximum radius too far, this operation can bog down PostGIS for densely populated urban areas. I'm mindful of the fact is operation also has a bulk endpoint, which multiplies the cost of search.

Let me know if you think it would be helpful to have a wider radius. I'm still open to increasing it a some more if it will be helpful.

**Comment by cblanc** [comment]
I'll close this issue for now. Please let me know if the current radius suffices for your needs.

**Comment by tomchambers2** [comment]
Ideally I'd be able to get the nearest postcode from any distance, but I imagine the query becomes exponentially more expensive as it increases. However the increase in usefulness falls off pretty quickly anyway, as most places in the UK are 2km from somewhere. So 2km will be sufficient for most purposes I think.

Thanks for the quick update and the API - its very useful.

**Comment by cblanc** [comment]
When I `EXPLAIN ANALYZE` radius search for densely populated areas the average latency jumps by an order of magnitude at around 5km compared to 1-2km. Almost all of this increase is due to sorting a very large set of postcode locations.

I suppose what I could do is create a new method which does a radius search over a progressively larger area until a small number of matches are found? That way you can guarantee a nearest postcode for any geolocation (within the UK).

I could expose a new endpoint for that, alternatively I could make it the dafault `nearest` method when the result limit is <=10 postcodes.

Would that be helpful?

**Comment by tomchambers2** [comment]
That's an interesting idea. I wouldn't worry about it too much for me if it
takes a significant amount of time, I'm using postcodes as a stopgap at the
moment since that's what my data is in, if my project is successful I'll be
searching directly by geo coordinates.

**Comment by cblanc** [comment]
Shouldn't be too much work. The only question in my mind is the best way to slot this into the API.

**Comment by cblanc** [comment]
I've updated /postcodes to accept a new flag `wideSearch` as part of your querystring (for GET) or body (for POST).

E.g. /postcodes/lon/0.35232/lat/52.328253?wideSearch=true

This returns the first 10 postcodes for up to a 20km search radius.

Also note that the "official" reverse geocoding API has changed. I.e. it's now /postcodes?lat=:latitude&lon=:longitude. But the old way of doing it will remain indefinitely.
