### ISSUE TITLE
[npm run setup] Hanging Saving to: ‘STDOUT’

### ISSUE THREAD

**Issue by BASE813** [ideal-postcodes/postcodes.io#237]
Everything is fine for the install on Debian 9.6 stretch up to this point where it hangs.

Any ideas

Connecting to postcodesio.s3.amazonaws.com (postcodesio.s3.amazonaws.com)|52.218.96.129|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 120278979 (115M) [application/x-sql]
Saving to: ‘STDOUT’
 0%[                                                                                                                       ]       0  --.-KB/s

**Comment by cblanc** [comment]
Hi there, thanks for the report.

I was able to run the script in a docker container with debian stretch and postgresql+postgis preinstalled [(mdillon/postgis:10)](https://github.com/docker-library/postgres/blob/master/10/Dockerfile)

For now, could you check if you could just `wget` the latest `pg_dump`. i.e.

```bash
wget https://postcodesio.s3.amazonaws.com/public/postcodesio-2018-12-10-1053.sql.gzl
```

It should write a `.sql.gz` file to your current directory

If the above works, I'll share the steps I took and we can compare notes

**Comment by BASE813** [comment]
Resolving postcodesio.s3.amazonaws.com (postcodesio.s3.amazonaws.com)... 52.218.96.81
Connecting to postcodesio.s3.amazonaws.com (postcodesio.s3.amazonaws.com)|52.218.96.81|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2018-12-19 11:10:04 ERROR 403: Forbidden.

**Comment by cblanc** [comment]
Apologies there was a stray `l` appended to that url. Should have read 

```
wget https://postcodesio.s3.amazonaws.com/public/postcodesio-2018-12-10-1053.sql.gz
```
