### ISSUE TITLE
Find the postcode a lat lng falls within

### ISSUE THREAD

**Issue by ultrasamad** [ideal-postcodes/postcodes.io#239]
Hi, apart from the endpoint that returns the nearest postcodes given a `lat` and `lng`, is there a way to find out which postcode a particular `lat` and `lng` falls within?

Thanks

**Comment by cblanc** [comment]
I'm afraid not. The reason for that is the geolocation data provided by ONSPD is the centroid of the postcode (i.e. a specific point) and not a bounding polygon. I'm not aware of a liberally licensed dataset that would facilitate this kind of query

**Comment by ultrasamad** [comment]
@cblanc Oh ok. thanks. But do have any resource you can point me to to achieve this?
