### ISSUE TITLE
Road name and House No.

### ISSUE THREAD

**Issue by Link2Twenty** [ideal-postcodes/postcodes.io#29]
If it possible to include a list of Road names and House No.'s that the post code could belong to? This would make live pop search for address possible, saving end users time and also helping keep the incoming data accurate

**Comment by cblanc** [comment]
With regards to road names. It should be possible to include a list of nearby road names based on data freely available within the public domain. My best lead so far is Ordnance Survey's OS Locator data - and I'm in the middle of figuring how best to infer a postcode's street based on the available information.

With regards to house numbers (or any premise identify information), I think this is not possible with the data currently available. The only authoritative data source for addresses is owned by Royal Mail and is not cheap to access. So I guess this won't be implemented any time soon. I am however pinning my hopes on @OpenAddressesUk - these guys are attempting to create and distribute a crowdsourced list of UK addresses. When that project has sufficient coverage, I'll be integrating that with this project.

**Comment by andrewcartwright1** [comment]
Was just wondering with OpenAddresses being in hibernation.. If there was any plans to look at alternatives? This Is one feature I'm looking at with great interest and hope to see added at one point if possible.

**Comment by cblanc** [comment]
Unfortunately the prospect of getting a complete (or complete enough) address list is now even more remote. As far as I know, there is no similar project going on (at least not one this well executed)

I've given some thought about opening up some endpoints on postcodes.io to accept address submissions, but the legal considerations that the OA team had to manage (like tracking provenance) is a massive and dangerous undertaking without proper resourcing.

OpenAddresses was well funded and staffed by some excellent developers. The level of planning and thoroughness they applied to the project was incredible. I wouldn't be surprised if they came back with more ideas to solve this problem after the hiatus.

**Comment by samjonesigd** [comment]
Any possibility of just street names? Then the user could just fill in number and post code to populate their address.
