### ISSUE TITLE
Incorporate IDs back into postcode dataset

### ISSUE THREAD

**Issue by cblanc** [ideal-postcodes/postcodes.io#30]
Original ID's were converted into names and then discarded when ingesting the ONS Postcode Directory. Add these back into the database and return them via the API.

**Comment by cblanc** [comment]
Reincoporating IDs as part of normalization exercise. Working branch is here: 48828d6f0557f7852d7c4af6400b850273454ce6

**Comment by stellard** [comment]
Awesome thanks @cblanc !

**Comment by cblanc** [comment]
The working branch has been merged into master. Will flip the switch later today or early tomorrow.

How it works: Postcode results now contain a `codes` object which store the ID provided by ONS. So a administrative district ID would look something like: `postcode.codes.admin_district`

**Comment by cblanc** [comment]
Ok. Should be live now

**Comment by stellard** [comment]
Works perfect. Thanks again @cblanc
