### ISSUE TITLE
Documentation does not state possibility of lat/long nulls

### ISSUE THREAD

**Issue by markembling** [ideal-postcodes/postcodes.io#310]
Querying a postcode from Jersey (in this case, JE2 4ST) returns the following result at time of writing:

```
{
    "status": 200,
    "result": {
        "postcode": "JE2 4ST",
        "quality": 9,
        "eastings": null,
        "northings": null,
        "country": "Channel Islands",
        "nhs_ha": "Jersey Health Authority",
        "longitude": null,
        "latitude": null,
        ...
    }
}
```

The `eastings` and `northings` are returning null, as expected based on the [documentation](http://postcodes.io/docs). However so are `longitude` and `latitude`, which the documentation does not specify as nullable.

**Comment by cblanc** [comment]
Thanks bud, put through the changes just now
