### ISSUE TITLE
Documentation does not state possibility of lat/long nulls for outcode lookup

### ISSUE THREAD

**Issue by markembling** [ideal-postcodes/postcodes.io#313]
Another minor documentation-related one from me... exactly the same issue as #310, but this time for the latitude and longitude fields described in the section which deals with the `/outcodes` API.

Response example (for `api.postcodes.io/outcodes/JE2`):
```
{
    "status": 200,
    "result": {
        "outcode": "JE2",
        "longitude": null,
        "latitude": null,
        ...
    }
}
```

I hope you don't mind me flagging these but its significant for me as I need to make sure [my library](https://github.com/markembling/MarkEmbling.PostcodesIO) maps such fields as nullable, and will potentially be true for others consuming the API from other languages which distinguish between value and reference types.

Thanks :-)

**Comment by cblanc** [comment]
Yes of course

Please continue flagging - any help catching bugs, errors, inconsistencies even down to edit distance 1 typos is hugely appreciated
