### ISSUE TITLE
Why no town to postcode?

### ISSUE THREAD

**Issue by digitaltoast** [ideal-postcodes/postcodes.io#325]
This is probably a stupid question, but why no "town/city name to postcode" option?

**Comment by cblanc** [comment]
Hi there

Firstly, you need to define town or city. That's quite important - it would be especially helpful if it falls into a categorisation scheme provided by ONS and is mapped to a postcode in ONSPD

However this isn't possible in practical terms. That type of request would produce a huge amount of data as a HTTP API

If you need to produce a list quickly however as a one time job, I recommend you just run the postgresql docker container and pass in a SQL query 

Example

```sql
SELECT * FROM postcodes WHERE admin_district_id='E07000079'; -- Find postcodes for "Cotswolds" (the administrative/local authority) district
```

**Comment by digitaltoast** [comment]
Good morning - late night, stupid question, wrongly worded, my apologies!

In fact, it was town name to geocode AND any postcode in that town that I needed, ie, type Aberdeen and get
Aberdeen | AB10 |  57.13 | -2.11 

I had a REALLY old database from 2014 from a now-defunct website called ukpostcodes.org

But of course, I now realise that I need to have it in my own DB to do the "nearest to this by geocode" anyway. I did find a more up to date "legal" CSV file in the form above, but I won't post the link here in case it conflicts with your commercial offering!

Hope that all makes sense - thanks for a fantastic product (which works great for what I need "the other way round" as it were!)
