### ISSUE TITLE
Documentation doesn't include incode/outcode for postcodes

### ISSUE THREAD

**Issue by markembling** [ideal-postcodes/postcodes.io#328]
Another minor documentation-related one from me.

A postcode lookup includes the following:

```
{
    "status": 200,
    "result": {
        ...
        "incode": "1AA",
        "outcode": "GU1",
        ...
    }
}
```

These don't appear in the table of available data fields for postcode lookups.

Thanks 👍

**Comment by cblanc** [comment]
Thanks bud, good catch
