### ISSUE TITLE
Allow search by parish

### ISSUE THREAD

**Issue by xavriley** [ideal-postcodes/postcodes.io#37]
I realise this is bit specific as a request, but would it be possible to return all the postcodes in a given parish somehow? As an example I'm looking at the Ewhurst parish (E04009613).

**Comment by cblanc** [comment]
I suppose it is a specific. I'm a bit hesitant to implement an endpoint for this though. A large number of parish IDs have thousands of associated postcodes (7 have north of 10k) - so some responses will be in the order of MBs

Are you looking to do this as a one-time thing? If so, you may be better off downloading the dataset and querying directly. All you need is Postgres + PostGIS. [Postgres.app](http://postgresapp.com/) is nicely packaged solution for OSX. Most linux package managers have outstanding support for Postgres + Postgis

The SQL queries should be quite straightforward, for instance:

```sql
SELECT * FROM postcodes WHERE parish_id='E04009613';
```

You can download and load our dataset into postgres using our setup script. Instructions here: https://github.com/ideal-postcodes/postcodes.io/wiki/Installing-Postcodes.io

You can download and import the data manually with 'psql' - I've updated the latest pg_dump just now: https://github.com/ideal-postcodes/postcodes.io/blob/master/latest. You can take a look at the [setup script itself](https://github.com/ideal-postcodes/postcodes.io/blob/master/bin/setup.sh) to see how it's done

**Comment by xavriley** [comment]
Perfect answer - thanks!

![screenshot 2015-05-20 13 43 08](https://cloud.githubusercontent.com/assets/369527/7725867/3b49faf4-fef6-11e4-9d27-b506094ba51c.png)

For the benefit of future users, the only issue I had was that I didn't have `postgis` installed initially so the db import wouldn't complete. It failed with:

```
ERROR:  could not open extension control file "/usr/local/Cellar/postgresql/9.4.1/share/postgresql/extension/postgis.control": No such file or directory
```

 But `brew install postgis` fixed that. Thanks again for a great project.
