### ISSUE TITLE
Incorrect validation/not found for NW1 2AU

### ISSUE THREAD

**Issue by iamwithnail** [ideal-postcodes/postcodes.io#373]
I was testing with this postcode (the coffee shop I was in!) and it's returning invalid postcode on the validation endpoint, and a 404 on the lookup endpoint.  Except it's definitely a real postcode - have tried in formats with both a space and no space - NW12AU / NW1 2AU.  

Postcode validates on other sites and comes up on Google/Apple Maps fine, but just seems to be a  mismatch on the data here - can you advise?

**Comment by cblanc** [comment]
Hi there 👋 

Appears to be terminated on April 2013

https//api.postcodes.io/terminated_postcodes/NW12AU

```json
{
  "status": 200,
  "result": {
    "postcode": "NW1 2AU",
    "year_terminated": 2013,
    "month_terminated": 4,
    "longitude": -0.129053,
    "latitude": 51.527733
  }
}
```

I checked Royal Mail's address file and it's not there either

Google/Apple maps don't do a good job of catching terminated postcodes. The internet does a good job of caching data in general - however I understand cache invalidation remains one of the 2 hardest problems in computer science  😄

**Comment by iamwithnail** [comment]
Oh, thanks!  I didn't think to check the terminated endpoint.  :man_facepalming:  I guess we have some workarounds to do on our end to deal with that, as this particular postcode still seems to be very much in use even though it's been finished.  :D That's fun.
