### ISSUE TITLE
api.postcodes.io/postcodes?lat=x&lon=x always returns result:null

### ISSUE THREAD

**Issue by hobochild** [ideal-postcodes/postcodes.io#374]
You can test on https://postcodes.io/

**Comment by hobochild** [comment]
the http status code is 200? so maybe client problem?

**Comment by cblanc** [comment]
Hi there

Believe it's working OK: http://api.postcodes.io/postcodes?lat=51.7923246977375&lon=0.629834723775

To understand how it works, imagine dropping a pin for the above geolocation on a map and drawing a circle around it. The results you get back are whatever points inside that circle

If the address is correctly formed (which appears to be the case given you're seeing `200`s) it's likely that:
1. The pin is way off somewhere where there are no postcodes - you need to fix your lat/lon inputs
2. The circle being drawn is too small - so it's not capturing any nearby points.

To fix 2 you can:
a. Increase the radius with `radius=` believe the default is `100` (metres). I think the max is `1000`
b. Use `wide_search=true` which is documented in postcodes.io/docs

**Comment by hobochild** [comment]
Thanks for the quick reply:

I'm running:
```
https://api.postcodes.io/postcodes?lon=-1.1743196999999999&lat=52.3555177
```
And it looks like google is finding a valid address:
https://www.google.com/maps/place/52%C2%B021'19.9%22N+1%C2%B010'27.6%22W/@52.3587675,-1.1981888,14.14z/data=!4m5!3m4!1s0x0:0x0!8m2!3d52.3555177!4d-1.1743197

Maybe google just has a wide_search?

**Comment by cblanc** [comment]
https://api.postcodes.io/postcodes?lon=-1.1743196999999999&lat=52.355517&radius=1000

Upping the radius would do it

**Comment by hobochild** [comment]
Makes sense thanks for walking me through it :+1:
