### ISSUE TITLE
SS17 postcode not supported

### ISSUE THREAD

**Issue by dwinnbrown** [ideal-postcodes/postcodes.io#376]
It seems that a valid UK postcode (SS17) is not supported. Would it be possible to look into this?

**Comment by cblanc** [comment]
Hi there

SS17 is an outcode (i.e. the first half of a postcode). You can search outcodes like so:

```
https://postcodes.io/outcodes/ss17
```

Also the API seems to be returning SS17 postcodes ok. Can test it like so

```
https://postcodes.io/random/postcodes?outcode=ss17
```

**Comment by dwinnbrown** [comment]
Hmm interesting the postcode I was trying was: SS17 7RT which doesn't seem to work? Definitely valid though according to royal mail. Fantastic plugin by the way!

**Comment by cblanc** [comment]
Seems to be there as well 😀

```
https://postcodes.io/postcodes/SS177RT
```

**Comment by dwinnbrown** [comment]
Ah not quite sure what's happened then as certainly wasn't working earlier...good news either way - thanks for the quick responses!

**Comment by cblanc** [comment]
If you have any more information about what you observed - e.g. response codes, request logs, would be great to know

Thanks for dropping by in any case
