### ISSUE TITLE
No way of determining if a postcode is not from Scotland, or just doesn't exist

### ISSUE THREAD

**Issue by mashedkeyboard** [ideal-postcodes/postcodes.io#388]
Thanks very much @cblanc for getting the Scottish postcodes stuff sorted! Woo! 🎉

One thing which is missing in this implementation is the ability to determine whether a postcode passed to the Scottish postcodes endpoint is 404ing because it doesn't exist, or 404ing because it's not in Scotland. Example:

- https://api.postcodes.io/postcodes/SW1A%200AA is fine and exists
- https://api.postcodes.io/scotland/postcodes/SW1A%200AA 404s as if it doesn't exist because it's not in Scotland

It'd be great if the endpoint could return something like "wrong country" or "postcode not in area" in such a scenario.

**Comment by cblanc** [comment]
I like the solution you presented - why not make a second request to `/postcodes/:postcode`?

Btw, theres a caveat emptor when combining the two datasets. SPD is about 6 months behind - so it's possible to not find a Scottish postcode in SPD and then find it in ONSPD

**Comment by mashedkeyboard** [comment]
Making a second request is possible, for sure, but if all you need to do is verify whether the postcode is in Scotland or not, making two requests when one would work seems overkill.

I've added some idea of what it might look like here, bearing in mind your point about SPD being behind: https://github.com/mashedkeyboard/postcodes.io

Will pull through a PR for it. :)

**Comment by cblanc** [comment]
Nice thanks 👍

I'll take a look and think it over
