### ISSUE TITLE
Question: Source for CCG19 codes.

### ISSUE THREAD

**Issue by willwade** [ideal-postcodes/postcodes.io#395]
Where does Postcodes source the latest CCG codes from? This to me looks like the most up-to-date list of CCG's: https://digital.nhs.uk/services/organisation-data-service/data-downloads/other-nhs-organisations but I don't see anywhere in the ccg data file - or anywhere on digital.nhs.uk a list of CCG19 codes (the code that postcodes.io is displaying). Does someone know where postcodes is sourcing these codes from? Arcgis has some - but there must be a more definitive source.

**Comment by cblanc** [comment]
They are the GSS codes for CCGs

https://geoportal.statistics.gov.uk/datasets/clinical-commissioning-groups-april-2019-names-and-codes-in-england

**Comment by willwade** [comment]
Thanks for that. So there isn't a permanent endpoint for those - do you guys get notified when there is a new version? Keeping track of changes is a pain. The CCG19CDH code is used across NHS data - which looks like its always more up to date than the GSS data. It will make matching data (its what we are doing with http://servicefinder.acecentre.net ) with CCG data a lot easier. Any chance for popping out the CCG19CDH in the codes section? "ccg-id" or something? I dare say not as it feels like a duplication.. but thought I should ask!

**Comment by cblanc** [comment]
Yes looks as though this is relatively straightforward. Will probably look like `ccg_id` in the `codes` object

Will schedule this in tandem with the ONSPD November release (so end Nov, I believe)

**Comment by willwade** [comment]
Woohoo! Thanks!
