### ISSUE TITLE
https://api.postcodes.io/places does not return data for Northern Ireland

### ISSUE THREAD

**Issue by francisbarton** [ideal-postcodes/postcodes.io#423]
https://api.postcodes.io/places?q=Oxford works but https://api.postcodes.io/places?q=Belfast (and other NI place names I have tried) does not return data. The site says it's UK data so my assumption would be that N Ireland places should be included.
(The [API documentation](https://postcodes.io/docs) says that the /places API returns a `country` string that refers to "one of the four constituent countries of the United Kingdom...")

**Comment by cblanc** [comment]
Hey sorry I didn't catch this earlier

Your point sounds valid. However the places dataset that powers `/places` is GB only

The mistake here is in the documentation, which has just been amended
