### ISSUE TITLE
channel island or isle of man postcodes return null long/lat

### ISSUE THREAD

**Issue by jjrdev** [ideal-postcodes/postcodes.io#426]
postcode based in channel islands, for example GY1 1AA and JE1 0BD or isle of man IM1 1AD  return null long/lat

curl http://api.postcodes.io/postcodes/GY1%201AA
curl http://api.postcodes.io/postcodes/JE1%200BD
curl http://api.postcodes.io/postcodes/IM1%201AD

an approximate result would be better than nulls

**Comment by cblanc** [comment]
May link an open dataset if people need this

Are there any liberally licensed datasets that provide this?
