### ISSUE TITLE
Fuming

### ISSUE THREAD

**Issue by greenlanegreb** [ideal-postcodes/postcodes.io#452]
People, I've just struggled for 10 hours with this. I don't understand why you have limited this to people who can code in JSON rather than, for example, allowing CSV's to be uploaded. I've struggled and struggled, i've read your documentation and the example within the bulk geolocation nearest postcode dialogue is entirely unclear. I presume you are providing two examples, one with switches, one without? If you actually didn't expect people that use your system to be expert programmers, maybe you might actually open it up to more people than watch people crash and burn having to deal with a shedload of arrogant programmers who tell you to go off and do it yourself on IRC. Fuming is a total understatement in terms of the entire lack of accessibility on this project.

**Comment by cblanc** [comment]
Hi there

I'd like to help but I'm not sure what you're having trouble with. Could you outline:
- What you're trying to accomplish
- How you're trying to do it
- What you expect to see 
- What you actually saw

Also, if you have feature requests like CSV upload or feel like there can be improvements made in the accessibility of the documentation, please let me know by opening an issue or contacting me along with specifics on what you're having trouble with.

> maybe you might actually open it up to more people than watch people crash and burn having to deal with a shedload of arrogant programmers who tell you to go off and do it yourself on IRC

I'm sorry you had to detail with difficult people on IRC. As the [primary maintainer](https://github.com/ideal-postcodes/postcodes.io/graphs/contributors) of this effort, I handle all queries related to postcodes.io myself. While we don't have an IRC channel, we do have [a rocket.chat instance](https://chat.ideal-postcodes.co.uk) you can reach me on

**Comment by cblanc** [comment]
Feel free to follow up if you need help
