### ISSUE TITLE
Feature Request: get by place name, i.e town 

### ISSUE THREAD

**Issue by MuhammadRahman-awin** [ideal-postcodes/postcodes.io#458]
Hi, 
This is a great tool, thanks a million for that. I think only thing missing is finding the lat/long from the name of the place, like town name.

Is there any chance you can add that to it.

Muhammad.

**Comment by cblanc** [comment]
Sorry took so long - did not see this notification

Have you tried the `/places` API ?

[http://postcodes.io/places?q=derry](http://postcodes.io/places?q=derry)
