### ISSUE TITLE
Is there a way to download the full data?

### ISSUE THREAD

**Issue by ahassaine** [ideal-postcodes/postcodes.io#460]
Hi there,

Many thanks for this brilliant tool.
Not sure where the data for this is stored but I was wondering if there is a way to download it directly?
More specifically, I need the list of postcodes and their associated Clinical commissioning group.

Many thanks,
Ali

**Comment by cblanc** [comment]
Easiest thing to do might be to run the database locally using docker and dispatch a SQL command to generate a CSV file. 

Have a brief guide here: https://ideal-postcodes.co.uk/guides/postcodes-io-database/

Briefly, steps to do this are:

1. Launch the DB

```bash
docker run -d -p 5432:5432 idealpostcodes/postcodes.io.db
```

Give it up to a min to ingest the pg_dump

2. Generate the CSV file with `psql

```bash
psql -h 0.0.0.0 --username postgres postgres -c "COPY (
SELECT 
    postcode, ccg_id, ccgs.name, ccgs.code, ccgs.ccg19cdh
  FROM postcodes 
  RIGHT OUTER JOIN ccgs 
  ON postcodes.ccg_id=ccgs.code
) to STDOUT DELIMITER ','" > output.csv
```

**Comment by ahassaine** [comment]
Many thanks for this !
