### ISSUE TITLE
Possible Encoding Issues: LL65 2UH

### ISSUE THREAD

**Issue by nodefortytwo** [ideal-postcodes/postcodes.io#53]
This might not actually be an issue on your side but I thought I would flag it anyway. Take a look at the parliamentary_constituency for LL65 2UH

It should be: Ynys Môn

But the encoding is incorrect. Not sure if this is a data source issues or your importing issue, or heaven forbid my own processing issue.

**Comment by cblanc** [comment]
This is not a problem on your end. The script used to ingest constituency data is not encoding input data correctly.

I've amended the database to fix that particular constituency. [http://postcodes.io/postcodes/LL652UH](http://postcodes.io/postcodes/LL652UH)

It seems 6 wards are affected by the same encoding issue. I'll leave this issue up until the scripts and the subsequent pg_dump is fixed

**Comment by nodefortytwo** [comment]
Amazing thanks for the quick turn around.
