### ISSUE TITLE
Postcode 404 / not found but works elsewhere -- how to find out why?

### ISSUE THREAD

**Issue by raisonon** [ideal-postcodes/postcodes.io#539]
For this postcode: sw6 5pn

I have tried:
http://api.postcodes.io/terminated_postcodes/sw65pn
as per this ticket: https://github.com/ideal-postcodes/postcodes.io/issues/373

and get: 

status | 404
error | "Terminated postcode not found"

Any ideas how to find out more information about this postcode and why it returns not found? Can find via other postcode services eg. https://www.zoopla.co.uk/for-sale/property/sw6-5pn/?q=sw6%205pn&radius=0.25&results_sort=newest_listings&search_source=refine

**Comment by cblanc** [comment]
Hi @raisonon 

It looks like Zoopla will always presents a result as long as the outward code is valid (SE6)

Things that seem odd:
- I've also grepped through Royal Mail's address file going back to 2014 and no luck
- I also looked for the first result on Zoopla for SW6 5PN (Tamworth Street SW6). The postcode for Tamworth Street is SW61LE
- The Zoopla results for that postcode point to a dozen different streets, which is impossible. I think the max is 2, and those instances are extremely rare

**Comment by raisonon** [comment]
I wonder if possible to replicate the Zoopla functionality of taking the first part (SE6) if a 404 is returned?
