### ISSUE TITLE
Suggestion to accept url encoded postcodes

### ISSUE THREAD

**Issue by neonwired** [ideal-postcodes/postcodes.io#56]
I think it'd be useful if it accepted url encoded postcodes, currently they don't work

**Comment by cblanc** [comment]
Could you provide an example? Thanks

**Comment by cblanc** [comment]
As far as I'm aware, the only url encoded characters applicable to postcodes is the space which can be encoded as `%20` before the query string and `+` within the query string

For the former, postcodes.io/postcodes/SW1%201AA yields the same response as postcodes.io/postcodes/SW1%201AA

Similarly for the latter, postcodes.io/postcodes?q=SW11AA yields the same response as postcodes.io/postcodes?q=SW1A+1AA

It would be great if you could provide me with your example where url encoding falls short. Thanks
