### ISSUE TITLE
Get all PostCode

### ISSUE THREAD

**Issue by kshkrao3** [ideal-postcodes/postcodes.io#65]
Is there any way to get all the post code with this API?

**Comment by cblanc** [comment]
A full list of postcodes would be a bit unwieldy to make available as an endpoint

You'd be better off using the the raw postcode list from ONSPD (http://webarchive.nationalarchives.gov.uk/20160105160709/http://www.ons.gov.uk/ons/guide-method/geography/products/postcode-directories/-nspp-/index.html)

Alternatively you could query our pg_dump of the database (https://raw.githubusercontent.com/ideal-postcodes/postcodes.io/master/latest)
