### ISSUE TITLE
Nearest postcodes - radius argument not working

### ISSUE THREAD

**Issue by erzk** [ideal-postcodes/postcodes.io#666]
Hi. It looks to me as if the `radius` argument is not working, e.g. both calls return the same number of results (22):

https://api.postcodes.io/postcodes/EC1Y8LX/nearest?limit=99?radius=100
https://api.postcodes.io/postcodes/EC1Y8LX/nearest?limit=99?radius=1900

I tried it with other postcodes and the results were the same.
Is this a bug?

**Comment by cblanc** [comment]
Hi there @erzk

Query string arguments should be separated with ampersands like this:

[https://api.postcodes.io/postcodes/EC1Y8LX/nearest?limit=99&radius=100](https://api.postcodes.io/postcodes/EC1Y8LX/nearest?limit=99&radius=100)
[https://api.postcodes.io/postcodes/EC1Y8LX/nearest?limit=99&radius=1900](https://api.postcodes.io/postcodes/EC1Y8LX/nearest?limit=99&radius=1900)

**Comment by erzk** [comment]
Doh!
