### ISSUE TITLE
admin_county is null for some postcodes

### ISSUE THREAD

**Issue by jpaylor** [ideal-postcodes/postcodes.io#691]
It seems some post codes are currently returning null for the county, when querying the live endpoint api.postcodes.io/postcodes/

**Example post code:** LS1 1UR

**Expected result:**

`"admin_county": "West Yorkshire",`

**Actual result:**

`"admin_county": null`

**Comment by cblanc** [comment]
Hi there

I'm afraid the `counties` label is a bit misleading in ONSPD. Admin counties, which is used by ONSPD, doesn't cover the whole of England. West Yorkshire CC was dropped in 1986 and is no longer [in the list](https://github.com/ideal-postcodes/postcodes.io/blob/master/data/counties.json). `admin_county` will be null for a lot of postcodes

Two my knowledge, there are only 2 types of county sets actively used/updated in England.

- [(Non) Metropolitan counties](https://en.wikipedia.org/wiki/Metropolitan_and_non-metropolitan_counties_of_England#Current_metropolitan_and_non-metropolitan_counties_of_England)
- [Administrative Counties](http://www.countycouncil.org.uk/)

Metro counties have their own drawbacks. It includes places like Thurrock, Luton while excluding the entire Greater London area. 

UK counties in general are problematic as they now only exist inside the heads of the UK population. The familiar counties most people grew up with mostly no longer exist for practical purposes and are certainly no longer captured in an authoritative dataset. As a result, it's not uncommon for people to contest that point X is in county { A, B, C } by citing a google result which shows one snapshot of county lines drawn at some time in the last 1000 years.

**Comment by jpaylor** [comment]
Hey @cblanc, thanks for the very comprehensive and prompt reply, that's interesting to learn. It may be worth referring to this or perhaps linking to this issue in the documentation for that field in case others run into the same query.

I understand that in order for you to include such counties in your database, you need a maintained dataset to refer to. It's an interesting dilemma because as you alluded to, while the counties may not exist from an admin/authority perspective, they are still very much in the heads of the UK population and, using the example of Yorkshire, it seems that North Yorkshire still 'exists' from an admin perspective (as there is North Yorkshire County Council) whereas West Yorkshire (which isn't a single council) does not. 

Again on this specific example, people very much perceive both Leeds and Bradford cities as being a part of the county of 'West Yorkshire'. Likewise, there are certain public services grouped under these counties e.g. 'West Yorkshire Police' or 'West Yorkshire Metropolitan Ambulance Service' and so on, so naturally, they might expect that a postcode in these areas would return 'West Yorkshire'.

I thought I'd do a bit of further research and found that while some services don't provide a county, some other services will return 'West Yorkshire' as the county for the postcode LS1 1UR, and wondered what they are linking it to. For example, a test of Google's place autocomplete API returned the following:

<img width="608" alt="image" src="https://user-images.githubusercontent.com/199908/105082598-ba733b00-5a8b-11eb-8b26-834f2eb99e0f.png">

Copied below in JSON format:
`{"address_components":[{"long_name":"LS1 1UR","short_name":"LS1 1UR","types":["postal_code"]},{"long_name":"Merrion Way","short_name":"Merrion Way","types":["route"]},{"long_name":"Leeds","short_name":"Leeds","types":["postal_town"]},{"long_name":"West Yorkshire","short_name":"West Yorkshire","types":["administrative_area_level_2","political"]},{"long_name":"England","short_name":"England","types":["administrative_area_level_1","political"]},{"long_name":"United Kingdom","short_name":"GB","types":["country","political"]}],"html_attributions":[]}`

They seem to be referring to it as a 'political' administrative area. I also noticed West Yorkshire is listed as a [metropolitan borough on Wikipedia](https://en.wikipedia.org/wiki/Metropolitan_borough).

Further to this, I've found a recent ONS dataset which appears to refer to it here: https://www.ons.gov.uk/datasets/mid-year-pop-est/editions/mid-2019-april-2020-geography/versions/1

In this file it seems to refer to West Yorkshire as "West Yorkshire (Met County)" and provides an "administrative-geography" code of `E11000006`.

**Comment by cblanc** [comment]
I'm hoping to have time next month to add one or two additional datasets from Ordnance Survey (outside of ONSPD/Codepoint open). I'm hoping there's a reasonable middle ground solution for counties. 

I'll keep a look out for West Yorkshire, though its hard to promise anything without there being an authoritative openly licensed dataset we can link to

**Comment by jpaylor** [comment]
Thanks @cblanc, appreciate it

I found another possible source, if you are able to use it: https://opendata.camden.gov.uk/Maps/National-Statistics-Postcode-Lookup-UK/tr8t-gqz7
