### ISSUE TITLE
Multi-arch Docker image (arm64 support)

### ISSUE THREAD

**Issue by billinghamj** [ideal-postcodes/postcodes.io#698]
It'd be awesome you could use Docker Buildx to provide a multi-arch image, so it's easy to deploy to arm64 machines.

I'm not quite sure how the Docker build process works for this repo - I can't see any obvious CI process for it, but might be able to assist if pointed in the right direction

**Comment by cblanc** [comment]
Hi @billinghamj. I'd like to know how to do this

These images are currently built on docker hub, tracking the master branch and new tags

**Comment by billinghamj** [comment]
In general it should be simple if you're able to use (or set up) Docker Buildx - eg in our builds we do:

```
            docker buildx create --use
             docker buildx build \
               --platform linux/amd64,linux/arm64 \
               --tag xyz:123 \
               --progress plain \
               --push \
               .
```

I know it's also super easy with GitHub actions. I'd think it's possible with Docker Hub - they do have a blog post about it, but not sure: https://www.docker.com/blog/multi-arch-build-and-images-the-simple-way/

**Comment by cblanc** [comment]
Hey @billinghamj - @mfilip had a look at this today and it seems the node image (API) can be built with arm64 but the database (postgis base image) lacks arm64 support. I suspect this may not be possible for the time being?

Do let me know if we missed something here

**Comment by billinghamj** [comment]
Ah yes that makes sense. I think it'd still be very useful for the application itself to be distributed with multiple architectures though? As it can be used without the database Docker image - e.g. we have always maintained our own database from before it was distributed with Docker
