### ISSUE TITLE
Create docker image

### ISSUE THREAD

**Issue by cblanc** [ideal-postcodes/postcodes.io#7]
Package postcodes.io in a docker image

**Comment by kachkaev** [comment]
Hi Chris, have you wrapped the app into docker in the end?

Just curious because I might be interested in bulk querying postcodes in in some future. Being able to just `git clone` and `docker-compose up` would be fantastic!

**Comment by cblanc** [comment]
I tried and gave up when docker was less mature on my native OS

It's probably time to give it a whirl again, am curious to see how docker has taken shape!
