### ISSUE TITLE
Missing postcode - SW18 1AG

### ISSUE THREAD

**Issue by adriandmitroca** [ideal-postcodes/postcodes.io#732]
The service doesn't have knowledge about postcode SW18 1AG.

https://www.streetcheck.co.uk/postcode/sw181ag

**Comment by cblanc** [comment]
The first address for this postcode was added on Oct 24th 2020. So it will be available in the next ONSPD release

**Comment by adriandmitroca** [comment]
Thanks for the info! Any idea when that will happen?

**Comment by cblanc** [comment]
Was hoping to do this this week, but I'm really slammed at the minute - so had to postpone to next

Likely Monday next week earliest or Wed latest

**Comment by cblanc** [comment]
Just deployed

http://postcodes.io/postcodes/sw181ag
