### ISSUE TITLE
Possible npm install missing in readme? 

### ISSUE THREAD

**Issue by xanderbailey** [ideal-postcodes/postcodes.io#770]
<img width="667" alt="Screenshot 2021-04-21 at 12 39 27" src="https://user-images.githubusercontent.com/20154192/115547800-9e578380-a29e-11eb-9e90-4a897d04eb69.png">
Was getting this error so needed to do `npm install` and then it all ran find (using MacOS). I think it just needs to be added to the docs maybe?

**Comment by cblanc** [comment]
Perhaps `npm run build` as well

**Comment by xanderbailey** [comment]
Will do it now!

**Comment by xanderbailey** [comment]
Getting an access denied to this repo?

**Comment by AshNaz87** [comment]
Have you forked the repo?
