### ISSUE TITLE
Including terminated postcodes

### ISSUE THREAD

**Issue by cblanc** [ideal-postcodes/postcodes.io#78]
Look into feasibility of including deprecated postcodes behind a querystring flag

**Comment by neilbmclaughlin** [comment]
Been checking an example postcode from data set I was using which was causing a problem (LS14 6PF). This post code returns 404 from postcode.io, is unknown to the Royal Mail site, flagged as 'No Longer In Use' by doogal.co.uk and handled OK by NHS Choices in location searches.
