### ISSUE TITLE
ONSPD & NHSPD dataset released for May 2021

### ISSUE THREAD

**Issue by 11harveyj** [ideal-postcodes/postcodes.io#780]
Hi,

Raising an "issue" here for a couple of new dataset releases.

A new ONSPD release has been made available:
https://geoportal.statistics.gov.uk/datasets/7b543e410eb74fa6a4690346222782fc/about

Also, potentially another datasource, found that a NHSPD dataset is available, not sure if Postcodes.io already uses it?
https://geoportal.statistics.gov.uk/datasets/f9922a4ddcb1402fb6a3a8664d9867b5/about

**Comment by cblanc** [comment]
Thanks for the reminder

Sorry about the wait. Have timed this update with a refresh of the infrastructure, which is why its taking longer than usual. Will have it done by end of next week latest

**Comment by 11harveyj** [comment]
Fantastic, thank you @cblanc 

Wasn't aware of that.

**Comment by cblanc** [comment]
Hi @11harveyj  - sorry forgot to update. The update has been shipped
