### ISSUE TITLE
make it clear commercial use of Northern Ireland data is not allowed

### ISSUE THREAD

**Issue by mtmail** [ideal-postcodes/postcodes.io#82]
As pointed out on the /about page
"Great Britain postcode data may be used under the terms of the OS OpenData licence. Northern Ireland postcode data may be used under the terms of the ONSPD licence" 

The ONSPD licence https://www.ons.gov.uk/methodology/geography/licences doesn't allow commercial use
"If you also use the Northern Ireland data (postcodes starting with “BT”), you need a separate licence for commercial use direct from Land and Property Services. We only issue a Northern Ireland End User Licence (for internal business use only) with the data." 

Personally I don't like their terms, especially labeling it open, but it's a important enough restriction to mention it to users of the service.

**Comment by cblanc** [comment]
Thanks, I've expanded the notice on the about page

**Comment by mtmail** [comment]
looks good!
