### ISSUE TITLE
how to install on Ubuntu 16 LTS

### ISSUE THREAD

**Issue by mtmail** [ideal-postcodes/postcodes.io#84]
Hi,

The installation instructions are among the best I've seen considering how many dependencies get installed. The instructions from 17 Oct 2014 cover Ubuntu 14. I've installed it on Ubuntu 16 in a virtual machine and below are my notes should you ever want to update the instructions. I think that's optional but it might safe you an hour or to debugging.
- Running `apt-get upgrade` grub asks which partitions to install bootrecords on. Sadly the question is interactive (even when setting `export DEBIAN_FRONTEND=noninteractive`) breaking any automated builds. A solution is executing `echo "set grub-pc/install_devices /dev/sda" | sudo debconf-communicate` before `apt-get upgrade`.
- Curl needs to be installed `sudo apt-get install curl`
- `python-software-properties python` is not required. I ran a successful full build without those.
- same for `pgadmin3`
- Instead of node 4 I installed node 6 (currently 6.7.0) like this:

```
# http://askubuntu.com/revisions/786279/6
sudo touch /etc/apt/sources.list.d/nodesource.list
echo "deb https://deb.nodesource.com/node_6.x xenial main" | sudo tee /etc/apt/sources.list.d/nodesource.list
echo "deb-src https://deb.nodesource.com/node_6.x xenial main" | sudo tee -a /etc/apt/sources.list.d/nodesource.list
curl -s https://deb.nodesource.com/gpgkey/nodesource.gpg.key | sudo apt-key add -
sudo apt-get update -qq
sudo apt-get install nodejs
```
- Instead of Postgres 9.3 I installed 9.5. 

```
sudo apt-get install -y postgresql-9.5-postgis-2.2 postgresql-contrib-9.5
```

Ubuntu sources already know about 9.5, there's no need to patch the `/etc/apt/sources.list` any more.
- buynan-syslog has a resolved issue (https://github.com/mcavage/node-bunyan-syslog/issues/39) with node 6 that requires it to be installed from github master instead of npm. Both have the same version (0.3.1) which is confusing. iconv needs to be updated though (https://github.com/bnoordhuis/node-iconv/issues/157), maybe even replacing with iconf-lite might be an option. Running these steps works but I see that as temporary fix only.

```
cd postcodes.io/
npm install mcavage/node-bunyan-syslog
npm install iconv@2.2.1 --save
npm install
```
- there's a warning `npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade`

**Comment by cblanc** [comment]
Thanks for the detailed write up, I've neglected to update the install instructions for a while.

I've updated the node.js and postgres instructions for (4.x and 9.5 respectively). I think keeping node at 4.x LTS is the simplest way to go until 6.x LTS is available (some time in Oct I think). Though I've made a note of manually installing the dependencies in a troubleshooting section. Also I think 4.0 means we don't need to ask to install curl

I think it would be best to omit `apt-get upgrade` altogether, this should be up to the end user as it could result in unintended consequences on other packages the user may be relying on
