### ISSUE TITLE
Return nearest Outcodes for a given Postcode.

### ISSUE THREAD

**Issue by k-x-d** [ideal-postcodes/postcodes.io#86]
Hi,

You currently have functionality to return the Nearest Postcodes given a Postcode, and the Nearest Outcodes given an Outcode. Both use the 'limit' and 'radius' parameters. It is possible to extend this to create an api that returns the Nearest Outcodes given a Postcode?

Thanks,

Kev

**Comment by mtmail** [comment]
Looks like related to https://github.com/ideal-postcodes/postcodes.io/issues/39

**Comment by k-x-d** [comment]
I read it a little differently; I thought #39 was about getting Outcodes based on a single Outcode. The current solution for which uses the relative centroid of the Outcode (in place of being able to search on the convex hull, which I understand would be based on all the postcodes in that Outcode??). 
I was asking about obtaining Outcodes based on a single Postcode. The single Postcode provided may not sit near the centre of the Outcode area (centroid or convex hull) but rather on the edge of the Outcode area. Consequently, the range of Outcodes return could differ. 

I'm new (really new) to all this and wouldn't be surprised if my reading of #39 was wrong. I'm grateful for your time and input. 

Cheers,

Kev

**Comment by cblanc** [comment]
Hi Kevin

#39 is somewhat related insofar that it would arguably improve accuracy by calculating the distance using the outer bound of a outcode (as opposed to the centroid)

However I think what you're looking for (retrieve nearest outcodes for postcode) can be achieved without having to modify the API.

1) Extract the outcode from the postcode by either:
1a) Make a call to `postcodes/:postcodes`
1b) Extract the outcode using a postcode parsing library (e.g. https://github.com/ideal-postcodes/postcode.js)

2) Make a call to `/outcodes/:outcode/nearest` using the extracted outcode

Hopefully that suffices, let me know if not

**Comment by k-x-d** [comment]
Hi,

Thanks. I'll give your suggestion a go. I'll come back if I have any further questions/pointers.

Cheers,

**Comment by k-x-d** [comment]
Just wanted to update that I have managed to work out a solution for my predicament. The code I developed is pasted below, if it's of use to anyone else. It works on the intended Wordpress (with WooCommerce) environment, though Ive not tested it extensively. Word of warning: I am very new to developing, so please review this code before using it.

`   


    //get billing_postcode from Woocommerce user meta data 
    //and extract the outcode portion  
    global $woocommerce;
    $user_billing_postcode = $woocommerce->customer->get_postcode();
    $full_postcode_in_array = explode (" ", $user_billing_postcode);
    $outcode_from_postcode = $full_postcode_in_array[0];

    //use the outcode portion to generate nearest outcodes
    $jsonAPIcall = "https://api.postcodes.io/outcodes/".$outcode_from_postcode."/nearest?limit=10&radius=7000";
    //echo out the API call so we can troubleshoot
    //echo $jsonAPIcall;

  
    $jsonCatchRestulsFromAPI = file_get_contents($jsonAPIcall);
    $jsonDecodedAPIResults = json_decode($jsonCatchRestulsFromAPI, true);


    foreach ($jsonDecodedAPIResults as $ResultsKey => $ResultsValue) 
    {
           echo $ResultsValue[0]["outcode"] . "<br>";
           echo $ResultsValue[1]["outcode"] . "<br>";
           echo $ResultsValue[2]["outcode"] . "<br>";
           echo $ResultsValue[3]["outcode"] . "<br>";
           echo $ResultsValue[4]["outcode"] . "<br>";
           echo $ResultsValue[5]["outcode"] . "<br>";
           echo $ResultsValue[6]["outcode"] . "<br>";
           echo $ResultsValue[7]["outcode"] . "<br>";
           echo $ResultsValue[8]["outcode"] . "<br>";
           echo $ResultsValue[9]["outcode"] . "<br>";
           echo $ResultsValue[10]["outcode"] . "<br>";

     }
     
`
