### ISSUE TITLE
Document data update process

### ISSUE THREAD

**Issue by SystemParadox** [ideal-postcodes/postcodes.io#860]
This was addressed in #63 a while back, but the documentation for this seems to have disappeared since then.

Please could we have some clear instructions on how to update the postcodes data for a running server (in particular, one running in docker)? Is live update still a possibility or do we have to completely rebuild?

I have tried deleting the containers and volumes and rebuilding but the dataset still seems out of date - the public postcodes.io site has the postcode, but it is still missing from my installation.

Thanks.

**Comment by cblanc** [comment]
Hi there

The old method was dropped in favour of the current docker approach.

If you're still getting the old data, it may be the new images aren't pulled. I'm not sure whats going on there, incrementing the version number on both the API and DB image should suffice.

I think if you're having trouble getting docker-compose/docker to comply with image version you can try to force -delete and -recreate the images
- You can shut down the current instances and remove the images with `docker-compose down --rmi all -v`
- Start up the `docker-compose up -d --force-recreate --build`

The DB container startup takes about a minute for the data to rehydrate

**Comment by SystemParadox** [comment]
You're right, it looks like it wasn't pulling the latest image for some reason - probably a bug in our docker scripts. I pulled manually and now it's updated.

I think it would be worth adding a specific section to the documentation to explain the official method of updating the data, even if that method is just "pull the latest image, delete the container and recreate it". If incremental updates aren't supported it would probably be worth stating this explicitly, especially since they used to be supported.

Something like:

```
## Updating the database

The docker image is periodically updated to the lastest ONS data.
To update your local installation, please pull the latest image and
recreate the container using the latest image. 

Live/incremental updates are not supported.
```

Thanks.
