### ISSUE TITLE
Any command / set of steps to be able to test new changes to the API *.ts files?

### ISSUE THREAD

**Issue by lerlands** [ideal-postcodes/postcodes.io#893]
I have spent time looking for ways to extend the idealpostcodes repository and API service. There are shape files available from official sources for OA, LSOA, MSOA, parish, wards, counties, constituencies and others. These can be converted into postgis files/commands that can be loaded as POLYGON data in the database, and searched for by lat/lon coordinates. I have done this, and it is working well. Happy to share...

I have developed new API controllers and models to access the shape data. I have spent aaages looking for ways to extend the API docker container to also accept the new 'ts' files. Complete failure. I have also tried to make subtle variations on existing controllers and model files to find a way for the docker container to accept the new changes, and make use of them. And I have failed. Again.

* Is there a set of steps to copy the api src directories into the containers, and re-compute the node server?
* Could the api src files maybe be set up as mounted directories in the container, rather than 'COPY' commands in the Dockerfile?
* Could the Makefile be extended with a target to allow typing 'make api' or something similar?
* Any clues to how I can help to develop this myself, and submit a pull request?

Thanks,
Lars Erlandsen.

**Comment by cblanc** [comment]
Hi Lars

Thats sounds like a great deal of work already. Perhaps you can push up your existing PR however rough. 

How to expose and query this data is almost a separate problem with lots of difficult tradeoffs in terms of performance and ergonomics

Our colleague @mfilip made a start a while back in this branch here, https://github.com/ideal-postcodes/postcodes.io/compare/boudaries, but we've been quite distracted lately so not much progress. Not sure what state this is in, but could be some help.

Wrt the docker image, it should be relatively straightforward to rebuild the API container. A `docker build` on the main Dockerfile will suffice - this should incorporate your new ts files. The hard part is adding the data. This is built with `Dockerfile.pg` which pulls down a compressed pg_dump. Of course, your work will not contain the new datasets so you would have to locally rebuild, and inject the updated pg_dump into the container.

- Any clues to how I can help to develop this myself, and submit a pull request?

Feel free to submit a draft/rough PR

**Comment by lerlands** [comment]
Hi, Christopher.

Thanks for speedy reply. Just the shot in the arm that I needed. Will try the hints, and report back.

Will get back with a rough pull request a little later. There is sooooo much good data available from official HM websites...
