### ISSUE TITLE
Missing Postcode

### ISSUE THREAD

**Issue by FattusMannus** [ideal-postcodes/postcodes.io#90]
This seems to be missing from your data: 
CF5 6XJ

A postcode somewhere in Cardiff - A search in Google confirms its ok

**Comment by mtmail** [comment]
https://www.doogal.co.uk/ShowMap.php?postcode=CF5%206XJ says the postcode is no longer in use
```
Date introduced:	June 1981
Date usage ended:	August 2015
```

**Comment by FattusMannus** [comment]
Hmm interesting - any ideas of what its replaced with?

**Comment by mtmail** [comment]
2012 data points to lon=-3.2720492861088, lat=51.462084148325 which is the building in the center of https://www.google.de/maps/@51.4620769,-3.2724819,358m/data=!3m1!1e3 (Google Earth view) There are no cars in the parking spaces while there are many cars in the rest of the industrial area. I'd say the building is abandoned and the postcode obsolete.

**Comment by cblanc** [comment]
That postcode was a television centre belonging to ITV Wales

Someone kindly posted images of the building being demolished beginning of 2015 (-:

http://www.walesonline.co.uk/business/business-news/gallery/culverhouse-cross-9059475 (pardon the HTV typo)

**Comment by mtmail** [comment]
Nice, you even found photos. I added a note for the local OSM mappers in that area http://www.openstreetmap.org/note/798694
