### ISSUE TITLE
NE3 3LZ is in the incorrect location

### ISSUE THREAD

**Issue by NickBosworth** [ideal-postcodes/postcodes.io#918]
Apologies if this is not the right forum to report this with it being data > code.

NE3 3LZ is in the incorrect location

https://www.google.com/maps/place/Gosforth,+Newcastle+upon+Tyne+NE3+3LZ/@55.0111429,-1.6245547,17z/data=!3m1!4b1!4m5!3m4!1s0x487e76cb557483d1:0x93cb088cce4628e8!8m2!3d55.0110637!4d-1.6226741

**Comment by cblanc** [comment]
You're right. Seems like Ordnance Survey have the wrong coords - the address and location don't line up. I'll drop a note to our liaison at OS - should be fixed in the next release

**Comment by cblanc** [comment]
You're right. Seems like Ordnance Survey have the wrong coords - the address and location don't line up. I'll drop a note to our liaison at OS - should be fixed in the next release
