### ISSUE TITLE
Pull back all postcodes to a constituency?

### ISSUE THREAD

**Issue by Ben-TangentDesign** [ideal-postcodes/postcodes.io#95]
Is it possible to pull back all postcodes to any given constituency?

**Comment by cblanc** [comment]
Hi Ben

Are you asking if all postcodes in this dataset have a parliamentary constituency? If so, ran a quick check, looks like the answer is some (12,265) don't: 

```
select count(*) from postcodes where parliamentary_constituency is null;
 count
-------
 12265
(1 row)
```
