### ISSUE TITLE
Different capitalization of postcodes results in different lat lng

### ISSUE THREAD

**Issue by MJeorrett** [ideal-postcodes/postcodes.io#958]
Hey, I have noticed today that different capitalisation of postcodes seems to result in different lat lngs e.g.:
- eh1 3at gives 55.953789, -3.188128
- EH1 3AT gives 55.95405, -3.187638

This seems odd behaviour as both "eh1 3at" and "EH1 3AT" represent the same real world entity and so should logically have the same lat lng.  It seems that this postcode has only gained a different "variant" since yesterday (as our CI pipelines had seemingly random test failures which passed yesterday, 24/02/2022, and we traced it back to this issue).

In order to fix this we can easily sanitise postcodes our end before they are passed to postcodes.io, but I wonder if a change to postcodes.io might be a better long term solution?

**Comment by cblanc** [comment]
Thanks for catching this. We updated to ONSPD Feb 2022 last week. This is probably due to caching. 

It appears that the cached results are likely purged by now - will add a step trigger a cache refresh for future deploys
