### ISSUE TITLE
Postcodes database fails to startup in an Azure Web App

### ISSUE THREAD

**Issue by simonziegler** [ideal-postcodes/postcodes.io#976]
Hi,

I have deployed the idealpostcodes/postcodes.io.db:latest docker image to an Azure Web App and have a database startup failure. The logging for this is shown in the attached gist. How can I fix this please?

Thanks,     Simon

https://gist.github.com/simonziegler/c60665036c01eb80c9484993fc339752

**Comment by simonziegler** [comment]
Thank - I shall. I'll report back

**Comment by mfilip** [comment]
> Thank - I shall. I'll report back

Any update on this?
