### ISSUE TITLE
BFPO Postcodes come back as invalid

### ISSUE THREAD

**Issue by JoshButterworth** [ideal-postcodes/postcodes.io#986]
We've noticed that British Forces Post Office postcodes come back as invalid postcodes, for example BF1 6FA. 

These are international locations but also at the same time valid UK addresses for sending post to service people and their families.

I tried the Post office address finder and was able to look them up successfully, Is there any chance these could be added to the postcodes.io database?

Here is a full list:

https://www.gov.uk/government/publications/british-forces-post-office-locations/british-forces-post-office-locations-updated-17-june-2019

**Comment by stevelillywhite** [comment]
This is causing a lot of problems for my company. Is there any chance this could be resolved? Or any timeline for when it might be able to be fixed?

**Comment by cblanc** [comment]
It's unlikely `BF1 *` postcodes will be added unless its directly added to ONS Postcode Directory
